version: "3"
services:
  web_cocoon:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3000:3000"
    volumes: 
      - ./cocoon:/opt/app
      - gem_cache_cocoon:/gems
    env_file: 
      - .env/development/database_cocoon
      - .env/development/web_cocoon
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_cocoon
  webpack_dev_server_cocoon:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3035:3035"
    volumes: 
      - ./cocoon:/opt/app
      - gem_cache_cocoon:/gems
    env_file: 
      - .env/development/database_cocoon
      - .env/development/web_cocoon
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  database_cocoon:
    image: postgres
    env_file: 
      - .env/development/database_cocoon
    volumes: 
      - db_data_cocoon:/var/lib/postgresql/data
volumes: 
  db_data_cocoon:
  gem_cache_cocoon: